[features]
seeds = false
[programs.devnet]
bs_anchor_project = "HCYLD8mbzbLQYbzzsdaRkp5ANHmMHrhtfH9o3tKgrPDp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ryan/.config/solana/id.json"

[scripts]
test = "node tests/bs-anchor-project.js"
